name: Build .NET application
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dotnet/cli@v2
        with:
          command: restore
      - uses: dotnet/cli@v2
        with:
          command: build
